---
title: "Final_Description_analysis"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("./"))
```


```{r, echo=FALSE}
d = read.csv('1st_Launch_Full.csv')
#d = d[d$Guess_the_Cost <= 2000,]
# load packages 
library(data.table)
library(dplyr)
library(tidyr)
library(foreign)
library(lmtest)
library(sandwich)
library(multiwayvcov)
```


```{r, include=FALSE}
#Functions for later use
standard_conf_int_95 = function(regression, n){
  r = coeftest(regression, vcovHC(regression))
  upper_bound = r[n,1] + 1.96* r[n, 2] 
  lower_bound = r[n,1] -1.96* r[n, 2]
  return (c(lower_bound,upper_bound))
}
```

```{r, include=FALSE}
#Process/clean variables- covariates
d<-data.table(d)
#English as primary language
d$English_as_primary<-d[,.(abs(d$English_as_primary-2))]
d$English_as_primary<-as.factor(d$English_as_primary)
#Male: original, male=1, female=2
d$Male<-d[,.(abs(d$Male-2))]
d$Male<-as.factor(d$Male)
#household income- as factor due to <20k, >100k, and do not answer
d$Household_Income<-as.factor(d$Household_Income)
#Other languages- Blank is only English, French 1, German 2, Other 3
d$Speaks_German<-as.numeric(d[,Other_Language_Spoken %like% "2"])
d$Speaks_French<-as.numeric(d[,Other_Language_Spoken %like% "1"])

#Drink Frequency- options are not linear 
d$Drink_Frequency<-factor(d$Drink_Frequency)

#Cab preference
d$Cab_Preference<-d[,.(abs(d$Cab_Preference-2))]

#Purchase Frequency- also not linear
d$Purchase_Frequency<-factor(d$Purchase_Frequency)
```


```{r,include=FALSE}

#survey question datalabels. This does not work perfectly....
#to be used in demographic barplots, with name.arg()
English_as_primary<-c("No","Yes")
Male<-c("Female","Male")
Household_Income<-c("<$20,000","$20,000 to $34,999","$35,000 to $49,999",
                    "$50,000 to $74,999","$75,000 to $99,999",">$100,000","Prefer not to answer")
Speaks_German<-c("No","Yes")
Speaks_French<-c("No","Yes")
Drink_Frequency<-c(">Weekly","Weekly","Monthly","Seldom","Never")
Cab_Preference<-c("No","Yes")
Purchase_Frequency<-c(">Weekly","Weekly","Monthly","Seldom","Never")

demographics_labels<-list(English_as_primary,Male,Household_Income,Speaks_German,Speaks_French,Drink_Frequency,Cab_Preference,Purchase_Frequency)


#demographics_labels[1]
```

#1. EDA and Cleaning
##Pre-cleaning
```{r}
demographics=data.table(d[,.(English_as_primary,Male,Household_Income,Speaks_German,Speaks_French,Drink_Frequency,Cab_Preference,Purchase_Frequency)])
par(mfrow=c(3,3))
#look at randomization/tracks 
barplot(prop.table(table(d$Track)), main="Distribution across Tracks, Normalized", names.arg = c(0:12))
#Important to note- 0 on barchart is N/A or attrition.
#demographic summary

for (i in (1:length(names(demographics)))){
  #print(summary(demographics[,..i]))
  barplot(table(demographics[,..i]),
           main=names(demographics)[i]
          #,names.arg = demographics_labels[i]
          )}
```

```{r}
#colnames(d)
summary(d$Guess_the_Cost)
summary(d$Guess_the_Cost[d$French_Purchasing_Page == 1]) #French language only
summary(d$Guess_the_Cost[d$German_Purchasing_Page == 1]) #German language only
summary(d$Guess_the_Cost[d$German_Purchasing_Page == 0 & d$French_Purchasing_Page == 0]) #English language only
hist(d$Guess_the_Cost[d$Guess_the_Cost],main="All Guesses",breaks=100,xlab= "Guessed cost")
```

##deduping/cleaning
```{r deduping}
library(data.table)
# Cleaning out incomplete responses before treament exposures
d <- d[!is.na(d$Track),]
#summary(d)
# Counting occurances of IP address and Geo-codes
d$geo_code <- paste(d$LocationLatitude, d$LocationLongitude)
dt = data.table(d)
dt[, `freq_geo` := .N, by = geo_code]
dt[, `freq_ip` := .N, by = IPAddress]
#class(as.data.frame(dt))
#dt
## Creatig 2 dedupped dataset, one with complete dedup where we do not allow any duplicates in IP or Geo code, and one where we exclude IP dupes, but allow up to 5 dups per geo code
complete_dedup<- dt[dt$freq_ip==1 & dt$freq_geo==1]
#nrow(complete_dedup)
five_or_less_dedup <- dt[dt$freq_ip==1 & dt$freq_geo<=5]
#nrow(five_or_less_dedup)
d<-five_or_less_dedup
```

##Post cleaning
```{r}
d<-data.table(d)
par(mfrow=c(3,3))
#look at randomization/tracks 
barplot(prop.table(table(d$Track)),main="Distribution across Tracks, Normalized",names.arg = c(0:12))
#Important to note- 0 on barchart is N/A or attrition.


for (i in (1:length(names(demographics)))){
  #print(summary(demographics[,..i]))
  barplot(prop.table(table(demographics[,..i])),
           main=names(demographics)[i])}

```
#Demographic/Covariate Balance Check


##Now looking at Outcome Variables
```{r}
summary(d$Guess_the_Cost)
#hist, includes all cleaned 
hist(d$Guess_the_Cost,main="All conditions",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d$Guess_the_Cost), col = "blue")
abline(v = median(d$Guess_the_Cost), col = "green")

#formats
par(mfrow=c(1,3))
#pin(c(2,2))
hist(d$Guess_the_Cost[d$French_Purchasing_Page == 1],main = "French format",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d$Guess_the_Cost[d$French_Purchasing_Page == 1]), col = "blue")
abline(v = median(d$Guess_the_Cost[d$French_Purchasing_Page == 1]), col = "green")

hist(d$Guess_the_Cost[d$German_Purchasing_Page == 1],main = "German format",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d$Guess_the_Cost[d$German_Purchasing_Page == 1]), col = "blue")
abline(v = median(d$Guess_the_Cost[d$German_Purchasing_Page == 1]), col = "green")

hist(d$Guess_the_Cost[d$German_Purchasing_Page == 0 & d$French_Purchasing_Page == 0 ],main = "English format", xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = median(d$Guess_the_Cost[d$German_Purchasing_Page == 0 & d$French_Purchasing_Page == 0]), col = "green")
abline(v = mean(d$Guess_the_Cost[d$German_Purchasing_Page == 0 & d$French_Purchasing_Page == 0]), col = "blue")

```
```{r}
#hist figures for origin, description, cleaned 
par(mfrow=c(2,2))

#Origins
d_chart=d$Guess_the_Cost[d$US_Origin == 1]
hist(d_chart,main = "US Origin Wine",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d_chart), col = "blue")
abline(v = median(d_chart), col = "green")

d_chart=d$Guess_the_Cost[d$US_Origin == 0]
hist(d_chart,main = "French Origin Wine",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d_chart), col = "blue")
abline(v = median(d_chart), col = "green")

#descriptions
d_chart=d$Guess_the_Cost[d$Long_Description == 0]
hist(d_chart,main = "Short Description",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d_chart), col = "blue")
abline(v = median(d_chart), col = "green")

d_chart=d$Guess_the_Cost[d$Long_Description == 1]
hist(d_chart,main = "Long Description",xlab= "Guessed cost", xlim = c(0,100),breaks=1000)
abline(v = mean(d_chart), col = "blue")
abline(v = median(d_chart), col = "green")
```