---
title: "sharad_rml"
author: "Sharad Varadarajan"
date: "August 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("./"))

library(MASS)
library(stargazer)
library(sandwich)
library(lmtest)

d = read.csv('1st_Launch_Full.csv')
```

```{r deduping}
library(data.table)
# Cleaning out incomplete responses before treament exposures
d <- d[!is.na(d$Track),]
#summary(d)
# Counting occurances of IP address and Geo-codes
d$geo_code <- paste(d$LocationLatitude, d$LocationLongitude)
dt = data.table(d)
dt[, `freq_geo` := .N, by = geo_code]
dt[, `freq_ip` := .N, by = IPAddress]
#class(as.data.frame(dt))
#dt
## Creatig 2 dedupped dataset, one with complete dedup where we do not allow any duplicates in IP or Geo code, and one where we exclude IP dupes, but allow up to 5 dups per geo code
complete_dedup<- dt[dt$freq_ip==1 & (dt$freq_geo == 1 | (dt$geo_code == 'NA NA' & Track!= ''))]
#nrow(complete_dedup)
five_or_less_dedup <- dt[dt$freq_ip==1 & dt$freq_geo<=5]
#nrow(five_or_less_dedup)
d<-complete_dedup



d$English_as_primary<-d[,.(abs(d$English_as_primary-2))]
d$English_as_primary<-as.factor(d$English_as_primary)
#Male: original, male=1, female=2
d$Male<-d[,.(abs(d$Male-2))]
d$Male<-as.factor(d$Male)
#household income- as factor due to <20k, >100k, and do not answer
d$Household_Income<-as.factor(d$Household_Income)
#Other languages- Blank is only English, French 1, German 2, Other 3
#d$Speaks_German<-as.numeric(d[,Other_Language_Spoken %like% "2"])
#d$Speaks_French<-as.numeric(d[,Other_Language_Spoken %like% "1"])
#Drink Frequency- options are not linear 
d$Drink_Frequency<-factor(d$Drink_Frequency)

#Cab preference
d$Cab_Preference<-d[,.(abs(d$Cab_Preference-2))]

#Purchase Frequency- also not linear
d$Purchase_Frequency<-factor(d$Purchase_Frequency)
```

#Attrition
```{r} 
attrit = subset(d, Finished == 0)
sum(attrit$French_Purchasing_Page == 1)
sum(attrit$German_Purchasing_Page == 1)
sum(attrit$French_Purchasing_Page == 0 & attrit$German_Purchasing_Page == 0)

lm_attrit_format = lm(Finished~French_Purchasing_Page + German_Purchasing_Page, d)
lm_attrit_origin = lm(Finished~ US_Origin, d)
lm_attrit_descrip = lm(Finished~Long_Description, d)

## Logistic regression
LR_format <- glm (Finished ~ French_Purchasing_Page + German_Purchasing_Page, data=d, family = binomial)
LR_origin <- glm (Finished ~ US_Origin , data=d, family = binomial)
LR_descrip <- glm (Finished ~ Long_Description, data=d, family = binomial)

stargazer(lm_attrit_format,lm_attrit_origin,lm_attrit_descrip,LR_format, LR_origin, LR_descrip, title="Attrition Regressions", align=TRUE, type="text")
```
##Covariate Balance Check

**The p-value on the Fstat is insignificant for all covariate balance regression tests, meaning we cannot reject the null hypothesis that all coefficients are equal to 0**
```{r}

d$French_Purchasing_Page = as.numeric(as.character(d$French_Purchasing_Page))
d$German_Purchasing_Page = as.numeric(as.character(d$German_Purchasing_Page))
d$US_Origin = as.numeric(as.character(d$US_Origin))
d$Long_Description = as.numeric(as.character(d$Long_Description))

#French vs English format
French_cb = lm(French_Purchasing_Page ~ Male + Household_Income + English_as_primary + Drink_Frequency + Cab_Preference + Purchase_Frequency, data = d[d$German_Purchasing_Page != 1,])

#German vs English format
German_cb = lm(German_Purchasing_Page ~ Male + Household_Income + English_as_primary + Drink_Frequency + Cab_Preference + Purchase_Frequency, data = d[d$French_Purchasing_Page != 1,])

#French vs German format
French_German_cb = lm(French_Purchasing_Page ~ Male + Household_Income + English_as_primary + Drink_Frequency + Cab_Preference + Purchase_Frequency, data = d[d$French_Purchasing_Page == 1 | d$German_Purchasing_Page == 1 ,])

#US Origin vs French Origin
Origin_cb = lm(US_Origin ~ Male + Household_Income + English_as_primary + Drink_Frequency + Cab_Preference + Purchase_Frequency, data = d)

#Long Description vs Short Description
LD_cb = lm(Long_Description ~ Male + Household_Income + English_as_primary + Drink_Frequency + Cab_Preference + Purchase_Frequency, data = d)

stargazer(French_cb,German_cb,French_German_cb,LD_cb, Origin_cb, title ="Covariate Balance Regressions", align=TRUE, type="text", font.size  = "tiny", column.sep.width = "0.5pt")


```



